version: '3'

services:
  redis:
    image: redis
    ports:
      - 3679:3697

  simple-counter:
    image: 127.0.0.1:5000/simple_counter
    build: ./node_service_counter
    volumes:
      - ./node_service_counter:/usr/src/app
    ports:
      - 8081:8081
    depends_on:
      - redis

  loadtest-master:
    image: 127.0.0.1:5000/loadtest_master
    build: ./loadtest_master
    volumes:
      - ./loadtest_master:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - redis

  loadtest-slave:
    image: 127.0.0.1:5000/loadtest_slave
    build: ./loadtest_slave
    volumes:
      - ./loadtest_slave:/usr/src/app
    depends_on:
      - redis
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: '50M'
